---
title: "Script"
author: "Victor"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}
pacman::p_load(shiny, shinydashboard, DT, dplyr, plotly, ggplot2, shiny, ggplot2, 
               tidyverse, data.table, plotly, ggrepel, shinydashboard, shinyWidgets, 
               shinythemes, ggtext, ggcorrplot, shinycssloaders, scales, shinydashboardPlus, gotop)
```

```{r import data}
UgandaDB <- data.table(read_csv("data/UgandaDB.csv"))

RwandaDB <- data.table(read_csv("data/RwandaDB.csv"))
```

```{r melt wide datasets into long format}
UgandaDB.long <- UgandaDB %>%
  pivot_longer(
    cols = starts_with(c("BAU", "Year")),
    names_to = "Year",
    names_prefix = NULL,
    values_to = "Amount",
    values_drop_na = TRUE
  )
View(UgandaDB.long)


RwandaDB.long <-RwandaDB %>%
  pivot_longer(
    cols = starts_with(c("BAU", "Year")),
    names_to = "Year",
    names_prefix = NULL,
    values_to = "Amount",
    values_drop_na = TRUE
  )
View(RwandaDB.long)

```

```{r clean the datasets}
UgandaDB.long$Amount <- as.numeric(gsub("\\$|,","", UgandaDB.long$Amount))

RwandaDB.long$Amount <- as.numeric(gsub("\\$|,","", RwandaDB.long$Amount))
```

```{r export the data}
fwrite(UgandaDB.long, "data/Uganda.csv")

fwrite(RwandaDB.long, "data/Rwanda.csv")

```

```{r Import Carbon dataset}
CarbonDB <- data.table(read_csv("data/CarbonDB.csv"))
```

```{r Remove the $ sign to clean the dataset}
CarbonDB$`Cumulative total institutional costs (US$/ha)` <- as.numeric(gsub("\\$|,", "", CarbonDB$`Cumulative total institutional costs (US$/ha)`))
CarbonDB$`Cumulative total individual costs to farmers/ha` <- as.numeric(gsub("\\$|,", "", CarbonDB$`Cumulative total individual costs to farmers/ha`))
```


```{r}
CarbonDB.long <- CarbonDB %>% 
  pivot_longer(
    cols = starts_with(c("Cumulative(tC/ha)",
                         "Cumulative total institutional",
                         "Institutional",
                         "Cumulative total individual",
                         "Individual")),
    names_to = "Type of investment",
    names_prefix = NULL,
    values_to = "Amount",
    values_drop_na = TRUE
  )
View(CarbonDB.long)
```

```{r export the data set}
fwrite(CarbonDB.long, "data/Carbon.csv")
```

